language: cpp

compiler:
    - gcc
    - clang

dist: trusty

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake clang

install: ./scripts/get-linux-deps.sh

script: ./scripts/travis-build.sh
